### PR TITLE
feat!: new API version

### LINKED ISSUE #20: Add support for raycasting
As a developer I want the ability to pick objects based upon my mouse location. 

https://threejs.org/docs/#api/en/core/Raycaster

### LINKED ISSUE #22: Default lighting
It would be beneficial to have the parameters for lighting to match the lighting used internally. A helper function could apply this lighting to the scen and a flag could enable/disable default lighting.

### LINKED ISSUE #189: Objects noticeably jitter / anchor issue
While using @googlemaps/three I've noticed that 3D objects rendered onto the map using `ThreeJSOverlayView` jitter.
https://drive.google.com/file/d/1uacSEtHdXIxr5tLRQtKwhRqog6vY_w5T/view?usp=sharing
Apparently this is related to the fact that the objects and the camera are too far from the world's origin. So when the vertices' positions are computed by the shader there's not enough fp precision (see `src/fp-precision` directory in the linked repo).
So I tried moving the world's origin closer to the camera for which the `anchor` property of `ThreeJSOverlayView` exists it seems. And indeed the jittering of the objects in this case is not observed (see `src/rel-coords` directory in the linked repo). However the coordinates (computed using `latLngToVector3Relative`) at which the objects are rendered are way off (except for the object which is located exactly at the anchor's position). Compare positions of red boxes which are not in the initial center in `fp-precision` and `rel-coords` in the linked repo.
So how to go about these issues?

#### Environment details

Windows 10 x64, Chrome (latest)

#### Steps to reproduce

Just clone the repo linked below and follow the README.

#### Code example

Here's the repo with the described issues:
https://github.com/MadOPcode/googlemaps-threejsoverlayview-issues

### LINKED ISSUE #613: Replace handling of three.js dependency with peerDependencies
The way the three.js dependencies are currently implemented is to pass an object with the three.js constructors and functions needed inside the library as a parameter to the constructor. 

This isn't Ideal since it exposes implementation details to the user and requires users to update their code when new features or even bugfixes are added that use new or different classes from the three.js library. This would unnecessarily make a lot of changes breaking changes.

Instead, the same behaviour can be implemented using package [peerDependencies](https://nodejs.org/es/blog/npm/peer-dependencies/) without putting too much burden on users.

In the library code, three.js objects are imported as usual using the ESM syntax with the `three` module alias:

```typescript
import {PerspectiveCamera, Scene, WebGlRenderer} from 'three'; 
```

The `three`-module referenced here isn't installed by `@googlemaps/three`, but has to be provided by the user and npm will check that a compatible version of three.js is used when installing.

The way this works in production is like this:
 - users building their apps using a bundler will be just fine, the import is resolved to the user-installed version of three.js
 - when using the UMD / ES5 build (via a script-tag from a CDN for example), users have to expose the three.js library via the global `THREE` object (which is the default when loading three.js via UMD)
 - when using the ESM build (e.g. a `<script type="module">` in html), users have to add an [importmap](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) to specify the url for the `three` module alias used in the library

As reference, here is another Addon for three.js that uses the exact same method described here (only that it is using microbundle instead of rollup): https://github.com/donmccurdy/three-pathfinding

### PR DESCRIPTION
**Pull request by usefulthink**
This adds several new features and breaking API changes to the package, summarized below:

## BREAKING CHANGES

 - db1ccd9: the three.js classes required by the overlay no longer need to be passed into the constructor. peerDependencies (bundled / ESM) and global scope lookups (UMD) are used instead (closes #613)
 - db1ccd9: direct ESM usage without importmaps is no longer supported
 - ce27d56: the default up-direction is now the z-axis, which is in line with the coordinates used within google maps
 - ce27d56: constructor parameters `rotation` and `scale` have been removed. Instead there is a new parameter `upAxis` that can be used to specify the rotation of the world-coordinate system
 - ce27d56: coordinate conversion has been fixed, instead of the `latLngToVector3*` functions, the new `overlay.latLngAltitudeToVector3()` should be used
 - 077b5eb: public property `overlay.anchor` replaced with private property and `setAnchor()` method
 - c93f45b: overlay will no longer keep running the animation loop to allow for energy efficient use (specify the `animationMode: "always"` option to get the previous behaviour back).

## New Features

 - f85b66: added `overlay.raycast()` to help with building interactive applications (closes #20)
 - a028aab: add `overlay.onBeforeDraw()` as a way to implement custom behaviour
 - c93f45b: new `animationMode` option to control if the overlay should keep rendering on every frame or only when requested
 - 24077d6: implement an option to add some default lighting to the scene that approximates the lighting used by the basemap (closes #22)

## Bugfixes

 - ce27d56: fixed positioning problems (fixes #189)

## Package Health

 - improved developer experience
 - fixed missing dependencies in es5-/umd-builds
 - code-cleanup + documentation
 - full test-coverage

BREAKING CHANGE: several API and behaviour changes

### CODE REVIEW

**Comment by usefulthink** [comment]
@amuramoto unfortunately, I can't resolve the merge-issues myself for this branch as I don't have write access. Is that something you can do or should I re-open this PR from a branch in my fork with resolved merge-conflicts?

**Comment by amuramoto** [comment]
@usefulthink I've set up the branch protection rules to allow you to write to the beta branch =D

**Comment by usefulthink** [comment]
that somehow didn't work (still getting `ERROR: Permission to googlemaps/js-three.git denied to usefulthink.`).

I now did the rebase manually, pushed it to my fork and created an updated PR in #656.

**Comment by amuramoto** [comment]
Merged! =D =D =D Amazing work on this!

**Pull request closed without merging**
